package com.be3c.sysmetic.domain.strategy.dto;

public enum StrategyAnalysisOption {

    /*

        StrategyGraphOption : 전략 상세 페이지 - 분석 지표 그래프 선택 기준

        STANDARD_AMOUNT : 기준가
        CURRENT_BALANCE : 잔고
        PRINCIPAL : 원금
        ACCUMULATED_DEPOSIT_WITHDRAWAL_AMOUNT : 누적 입출 금액
        DEPOSIT_WITHDRAWAL_AMOUNT : 일별 입출 금액
        DAILY_PROFIT_LOSS_AMOUNT : 일 손익 금액
        DAILY_PROFIT_LOSS_RATE : 일 손익율
        ACCUMULATED_PROFIT_LOSS_AMOUNT : 누적 손익 금액
        CURRENT_CAPITAL_REDUCTION_AMOUNT : 현재 자본 인하 금액
        CURRENT_CAPITAL_REDUCTION_RATE : 현재 자본 인하율
        AVERAGE_PROFIT_LOSS_AMOUNT : 평균 손익 금액
        AVERAGE_PROFIT_LOSS_RATE : 평균 손익률
        WINNING_RATE : 승률
        PROFIT_FACTOR : Profit Factor
        ROA : ROA
    */
    STANDARD_AMOUNT,
    CURRENT_BALANCE,
    PRINCIPAL,
    ACCUMULATED_DEPOSIT_WITHDRAWAL_AMOUNT,
    DEPOSIT_WITHDRAWAL_AMOUNT,
    DAILY_PROFIT_LOSS_AMOUNT,
    DAILY_PROFIT_LOSS_RATE,
    ACCUMULATED_PROFIT_LOSS_AMOUNT,
    CURRENT_CAPITAL_REDUCTION_AMOUNT,
    CURRENT_CAPITAL_REDUCTION_RATE,
    AVERAGE_PROFIT_LOSS_AMOUNT,
    AVERAGE_PROFIT_LOSS_RATE,
    WINNING_RATE,
    PROFIT_FACTOR,
    ROA
}
